### ISSUE TITLE
xdg-open doesn't open folders

### ISSUE THREAD

**Issue by bochecha** [flatpak/flatpak-xdg-utils#5] opened 2018-01-15 10:21 UTC
I originally reported this against Transmission (https://github.com/flathub/com.transmissionbt.Transmission/issues/4) because I thought the bug was there, but after investigation it seems not.

Inside a Flatpak sandbox:

```
bash-4.3$ xdg-open file:///home/mathieu/Downloads
bash-4.3$ 
```

The command exits successfully (it returns 0) and silently but nothing happens.

With the "classic" (i.e not Flatpak) xdg-open, a Nautilus window pops up showing the folder.

**Comment by wjt** [comment] 2018-01-15 13:43
Could you run `dbus-monitor` inside the sandbox, then run xdg-open? I have a memory of seeing an issue where xdg-open terminates before the recipient of its method call is activated, causing dbus-daemon to discard the method call.

**Comment by fmuellner** [comment] 2018-01-15 16:56
Probably a duplicate of [this portal issue](https://www.github.com/flatpak/xdg-desktop-portal/issues/128).

**Comment by wjt** [comment] 2018-11-19 11:07
Agreed. This now works with xdg-desktop-portal 1.0.3.

**Comment by hadess** [comment] 2018-11-19 11:52
> Agreed. This now works with xdg-desktop-portal 1.0.3.

OK, closing. @bochecha, please reopen if the problem is still there.

**Closed by hadess** 2018-11-19 11:52 UTC

**Comment by bochecha** [comment] 2018-11-19 14:41
@hadess I just tried it, it indeed works. Thanks to whoever fixed it! :slightly_smiling_face:

**Comment by rubenwardy** [comment] 2023-01-30 16:54
How do I apply this fix to our flatpak? See https://github.com/flathub/net.minetest.Minetest/issues/29
