### ISSUE TITLE
can't spawn a shell

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/flatpak-xdg-utils#15] opened 2018-12-16 17:54 UTC
Trying to spawn a shell gives some unexpected output. 

```
sh-4.3$ flatpak-spawn sh
sh: cannot set terminal process group (-1): Inappropriate ioctl for device
sh: no job control in this shell
```

**Comment by 1player** [comment] 2022-07-09 11:04
Duplicate of #57

**Comment by TingPing** [comment] 2022-07-09 16:55
Duplicate of #57

**Closed by TingPing** 2022-07-09 16:55 UTC
